### ISSUE TITLE
Include santizers into the CI

### ISSUE THREAD

**Issue by vmayoral** [AcutronicRobotics/moveit_ci#2]
This follows from https://discourse.ros.org/t/introducing-ros2-sanitizer-report-and-analysis and particularly:
- https://github.com/AcutronicRobotics/moveit2/pull/113
- https://github.com/vmayoral/basic_robot_cybersecurity/tree/master/robot_vulnerabilities/tutorial2

Ideally we should compile the code with the right flags to enable the sanitizers and somehow make the resulting `sanitizer_report.csv` available.

**Comment by vmayoral** [comment]
What are your thoughts on this @LanderU and @ahcorde?

**Comment by LanderU** [comment]
+1

**Comment by LanderU** [comment]
We should include the necessary flags here: https://github.com/AcutronicRobotics/moveit2/blob/master/.travis.linux.env#L6

**Comment by vmayoral** [comment]
That is right and we also need to install the right things to support ASan
and other sanitizers.
